n = input('Digite algo coisa : ')
print("A variável {} é do tipo : ".format(n), type(n))
print("É um número ? ", n.isnumeric())
print("É alfabético ? ", n.isalpha())
print("É alfanúmerico ? ", n.isalnum())
print("Está com todas letras em maiúsculo ? ", n.isupper())
print("Está com todas letras em minúsculo ? ", n.islower())
print("Está capitalizada ? ", n.istitle())
print("Só tem espaços ? ", n.isspace())